### ISSUE TITLE
Sailor does not reliably publish large messages

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/sailor-nodejs#127]
# Bug Report

## Description

When multiple large messages (that are still less than 10 MB) are published, they do not reliably arrive.

## Preconditions

Deploy a version of the code component with sailor version 2.6.0 ([such as this commit](https://github.com/elasticio/code-component/tree/d67bfe5340a1552e05e672d9dc479e0185d32c01)).

## Environment

* [x] Popeye
* [ ] Great Moraq (development)
* [ ] Essos (stage)
* [ ] Westeros (production)

## Steps to Reproduce

1. Create a flow of the from *Code component with sailor 2.6.0* -> *Code component with sailor 2.6.0* 
  * For the first step use the code snippet
  ```
  async function run(msg, cfg, snapshot) {
    const longString = (new Array(1024*1024*7)).join('a');
    for(let i = 0; i < 10; i++) {
        var data = messages.newMessageWithBody({
            i,
            data: longString
        });
        await emitter.emit('data', data);
        this.logger.info(`Published message ${i}`);
    }
  }
   ```
  * For the second code component use the snippet 
  ```
  async function run(msg) {
    const body = { result : 'Hello world!' };
    // You can emit as many data messages as required
    await this.emit('data', { body });
  }
  ```
  * Manually save `{}` as both samples.
2. Publish and run the flow.

## Actual Result
* Only a single message is produced every execution (for each component).
* Text similar to the following appear in the logs indicating an error
`Buffer full when publishing a message to exchange=59b11ca941e98200195eb6e3_org with routingKey=59b11ca941e98200195eb6e3.5e173bb8129b6e0013a680bc/ordinary.step_1.message`

## Expected Result
* 10 Messages are produced for each component on every execution.
* No log statements about `Buffer full` appear in the logs.

**Comment by zuker** [comment]
Seems `drain` event http://www.squaremobius.net/amqp.node/channel_api.html#channel_events is never published and async emit is never resolved. Seems like amqplib bug

**Comment by zuker** [comment]
Bug introduced in 2.2.3

**Comment by jhorbulyk** [comment]
The problem appears to persist even with sailor 2.6.1.  Here is the the commit of the code component that was used: https://github.com/elasticio/code-component/tree/42950d6c33987c0e5aa50024b83dd177978bb149

**Comment by zuker** [comment]
Found root cause and confirmed it.
Here https://github.com/elasticio/sailor-nodejs/blob/master/lib/amqp.js#L119 sailor starts listening for `drain` event AFTER message publish is confirmed, based on **resolved** return value of `publish` here https://github.com/elasticio/sailor-nodejs/blob/master/lib/amqp.js#L137. The thing is that `drain` happens earlier than confirm callback here https://github.com/elasticio/sailor-nodejs/blob/master/lib/amqp.js#L133 is called. 
To fix the problem sailor must listen on drain **immediately** after `false` is returned from `publish`, not after the confirm callback is called.

**Comment by zuker** [comment]
Something like this
```javascript
const promisifiedPublish = async (exchangeName, routingKey, payloadBuffer, options) => {
            let result;
            const publishPromise = new Promise((resolve, reject) => {
                result = publishChannel.publish(exchangeName, routingKey, payloadBuffer, options, (err, ok) => {
                    err ? reject(err) : resolve(ok);
                });
            });
            await Promise.all([
                (async () => {
                    if (this.settings.PROCESS_AMQP_DRAIN) {
                        if (result) {
                            return result;
                        } else {
                            log.debug('Amqp buffer is full: waiting for drain event..');
                            await eventToPromise(this.publishChannel, 'drain');
                            log.debug('Amqp buffer drained!');
                            return true;
                        }
                    } else {
                        return result;
                    }
                })(),
                publishPromise
            ]);
            return result;
        };
```
