### ISSUE TITLE
Update @elastic.io/maester-client to new version to avoid vulnerability

### ISSUE THREAD

**Issue by A3a3e1** [elasticio/sailor-nodejs#206]
Update to whatever new version there will be after the fix https://github.com/elasticio/maester-client/issues/40

Upd: Should be updated to 5.0.2-dev.5

**Comment by HannaTrotsenko** [comment]
New sailor version is [2.7.2](https://github.com/elasticio/sailor-nodejs/releases/tag/2.7.2)
