### ISSUE TITLE
`Rebound limit exceeded` message should be located in the step where it was emitted

### ISSUE THREAD

**Issue by if0s** [elasticio/sailor-nodejs#213]
# Component Bug Report

## Description

Currently, if we use the rebound feature, after 21 attempts to rebound we get an error message that will be located in the previous step rather than in the step that triggered the rebound.

Rebound and error is somewhere here:
[Sailor rebound](https://github.com/elasticio/sailor-nodejs/blob/77b2fc258be043429ed7af75ecd4fb1d28305c89/lib/amqp.js#L498)
[Sailor "Rebound limit exceeded" on last iteration](https://github.com/elasticio/sailor-nodejs/blob/77b2fc258be043429ed7af75ecd4fb1d28305c89/lib/amqp.js#L513)

## Version

2.7.3

## Steps to Reproduce

1. Create flow where first step will be webhook and second [REST API v2](https://github.com/elasticio/rest-api-component-v2) component
2. Enable `Retry on failure` in config and place there URL that will respond with 429 error
3. Run flow and wait until last rebound will be triggered

## Actual Result

Error `Rebound limit exceeded` in first step - webhook:
![image](https://github.com/user-attachments/assets/4d1f38bf-54e9-466f-9a06-b80bccb26f9f)
![image](https://github.com/user-attachments/assets/c97c8b5a-0c59-4df8-bcd5-286caf9e6795)

## Expected Result

Error in second step - REST API v2: 
![image](https://github.com/user-attachments/assets/a695c009-9864-4a5e-9642-73b4612f04fa)

## Workaround(s)

none

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/sailor-nodejs/releases/tag/2.7.4
