### ISSUE TITLE
Exceptions from VerifyCredentials are not caught and logged

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/sailor-nodejs#58]

**Comment by zubairov** [comment]
I assume 'exceptions' here means something like:

```js
function verifyCredentials() {
   throw new Error("I'm exceptional!');
}
```

Right?

May you also try something like this:

```js
function verifyCredentials() {
   return Promise.reject(new Error("I'm exceptional!"));
}
```

**Comment by jhorbulyk** [comment]
Correct.  The latest version of sailor is designed so that exceptions thrown from actions and triggers do not have to be wrapped in promises.  It would appear as though that modification was not applied to ``verifyCredentials()``.

**Comment by zuker** [comment]
It seems this is a case when component's container exits with exit code > 1, this splits into two cases:
1. `throw new Error()` in the `verifyCredentials()` method
2. Syntax error in the component's code.
In the first case, we can just wrap code with try/catch
In the second case, we can only store an error with something with `INTERNAL_ERROR`, like in lookout when it handles container exit.

**Comment by drobiazko** [comment]
@zuker would that partially solve 2.? https://github.com/elasticio/elasticio-buildpack-nodejs/issues/9

**Comment by jhorbulyk** [comment]
Case 1. was what I had in mind when I wrote this issue.  I believe that case #2 can be solved by elasticio/elasticio-buildpack-nodejs#9

**Comment by zubairov** [comment]
Couldn't we modify sailor to catch this exception when we do

``required(file_where_action_is_defined)``?

**Comment by drobiazko** [comment]
Of course we can but this would happen in runtime. We can increased developer's turnaround time by checking this as early as possible.

**Comment by zubairov** [comment]
cool. But our common understanding is that we should do both right? Try to 'load' all of the files at the build time and if exception happens in ``verifyCredentials`` we will use same mechanics as we use already in acitons and triggers right?

**Comment by drobiazko** [comment]
sure, validating and providing meaningful error messages at buildtime and runtime decreases the developer's frustration.

**Comment by zubairov** [comment]
@drobiazko would you be able to plan it into the next sprint backlog?

**Comment by PaulAnnekov** [comment]
Closed in favor of https://github.com/elasticio/elasticio/issues/4976 epic.
