### ISSUE TITLE
Static flow control (sailor)

### ISSUE THREAD

**Issue by zubairov** [elasticio/sailor-nodejs#76]
Currently when component code does:

```
this.emit('data', {});
```

Message is encoded, encrypted and sent to RabbitMQ channel [here](https://github.com/elasticio/sailor-nodejs/blob/master/lib/amqp.js#L107). Unfortunately there are following problems with this use:

1.  Result of the `publish` method is ignored (it returns `true` or `false`, in case of `false` we need to wait for `drain` event)

1.  In the situations when component call `emit` faster than underlying RabbitMQ layer could serialize and send data out of memory we are getting memory management problem (OOMs)

1. We have no way to limit the publishing rate to the queue which is an essential feature for flow control and (possibly) QoS enforcement

We need to fix that as following:

- [x] Make sure `emit` (as well as all other methods of sailor API that may result in networking operations e.g. snapshot) return a promise

- [x] Make sure we have a static rate limits for following operations:

   - [x] Emitting data, default value 200 messages per second
   - [x] Emitting errors, default value 20 per second
   - [x] Emitting snapshots, default value 20 per second

  - [x] Make sure all limits above can be changed from default value with help of environment variables
  - [x] Make sure documentation for sailor is updated with information about rate limits as well as with information (example) on how to use them (e.g. use the await for the promise after each operation)

**Comment by zubairov** [comment]
After more conversations with RabbitMQ experts, we should use `ConfirmationChannel` that already supports callbacks and [this](http://www.rabbitmq.com/confirms.html) RabbitMQ feature. Nevertheless rate limit should be imposed by `sailor` independent of the build-in rate limit inside the RabbitMQ.

**Comment by ElBabbler** [comment]
I hope [this](https://www.npmjs.com/package/function-rate-limit) lib could hepl us

**Comment by zubairov** [comment]
or [this](https://www.npmjs.com/package/p-limit) :)

**Comment by ElBabbler** [comment]
Found [this](https://glebbahmutov.com/blog/promisify-event-emitter/) decision to imlpement returning promise from emit.

**Comment by zubairov** [comment]
> Found [this](https://glebbahmutov.com/blog/promisify-event-emitter/) decision to imlpement returning promise from emit.

interesting, let's implement the return first then we can experiment on the `on` approaches.
